/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AgcToaster {
    'showToast': (notification: any) => void;
  }
  interface AgcToasterAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AgcToaster': Components.AgcToaster;
  }

  interface StencilIntrinsicElements {
    'agc-toaster': Components.AgcToasterAttributes;
  }


  interface HTMLAgcToasterElement extends Components.AgcToaster, HTMLStencilElement {}
  var HTMLAgcToasterElement: {
    prototype: HTMLAgcToasterElement;
    new (): HTMLAgcToasterElement;
  };

  interface HTMLElementTagNameMap {
    'agc-toaster': HTMLAgcToasterElement
  }

  interface ElementTagNameMap {
    'agc-toaster': HTMLAgcToasterElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
